#!/bin/bash

# Simple FTP upload for images
echo "🚀 Manual FTP Upload Instructions"
echo ""
echo "Since automated FTP is having issues, here's how to upload manually:"
echo ""
echo "1. Connect to FTP:"
echo "   ftp 106.0.62.101"
echo ""
echo "2. When prompted, enter:"
echo "   Username: christinaday@christinamday.com"
echo "   Password: [your hosting password]"
echo ""
echo "3. Navigate to the right directory:"
echo "   cd public_html"
echo "   mkdir images"
echo "   cd images"
echo "   mkdir fab-lab"
echo "   cd fab-lab"
echo ""
echo "4. For each project folder, you'll need to:"
echo "   mkdir \"Project-Name\""
echo "   cd \"Project-Name\""
echo "   mput /path/to/local/project/folder/*"
echo "   cd .."
echo ""
echo "📁 Your local images are in: $(pwd)/public/images/fab-lab/"
echo ""
echo "💡 Tip: This will take a while with 647 images. Consider using FileZilla GUI instead!"
echo ""
echo "🌐 FileZilla settings:"
echo "   Host: 106.0.62.101"
echo "   Username: christinaday@christinamday.com"
echo "   Password: [your password]"
echo "   Port: 21" 